# The URL the site will be built for
base_url = "https://furtidev.github.io"

# title & description for the site
description = "Personal blog of furti discussing software, manga and games."
title = "furtidev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
	{ name = "tags", feed = true},
]
generate_feeds = true
feed_filenames = ["rss.xml"]
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
external_links_target_blank = true

[markdown.highlighting]
style = "inline"
theme = "kanagawa-dragon"

[extra]
# Put all your custom variables here
